name: stimulus_reflex_expo

on_project_start: lsof -t -i tcp:3000 | xargs kill -KILL && lsof -t -i tcp:3035 | xargs kill -KILL
pre_window: asdf local ruby 2.7.1; asdf local nodejs 12.18.3

windows:
  - editor: nvim
  - console: bundle exec rails c
  - server:
      layout: main-vertical
      panes:
        - bundle exec rails s
        - bin/webpack-dev-server
  - worker: bundle exec sidekiq -C config/sidekiq.yml
